language: python
sudo: false
python:
  - 3.5
  - 3.6
  - nightly
env:
  - TASK=test
  - TASK=integration
matrix:
  include:
  - python: 3.6
    env: TASK=checks
  exclude:
  - python: nightly
    env: TASK=integration
install:
  - pip install tox-travis
script:
  - tox
